In [22]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file reading and writing
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [23]:
datasets = "./datasets/datasets - crop irrigation.csv"
raw_data = pd.read_csv(datasets)
raw_data.head()

  CropType  CropDays  SoilMoisture  temperature  Humidity  Irrigation
0    Wheat        10           400           30        15           0
1    Wheat         7           200           30        32           0
2    Wheat         9           300           21        28           0
3    Wheat         3           500           40        22           0
4    Wheat         2           700           23        34           0

In [24]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CropType      501 non-null    object
 1   CropDays      501 non-null    int64
 2   SoilMoisture  501 non-null    int64
 3   temperature   501 non-null    int64
 4   Humidity      501 non-null    int64
 5   Irrigation    501 non-null    int64
dtypes: int64(5), object(1)
memory usage: 23.6+ KB

In [25]:
X = raw_data.drop('Irrigation', axis="columns")
Y = raw_data['Irrigation']
X["CropType"].unique()

array(['Wheat', 'Groundnuts', 'Garden Flowers', 'Maize', 'Paddy',
       'Potato', 'Pulse', 'Sugarcane', 'Coffee'], dtype=object)

In [26]:
label_encoder = preprocessing.LabelEncoder()
X['CropType'] = label_encoder.fit_transform(X['CropType']) # encode the crop type label
X

     CropType  CropDays  SoilMoisture  temperature  Humidity
0           8        10           400           30        15
1           8         7           200           30        32
2           8         9           300           21        28
3           8         3           500           40        22
4           8         2           700           23        34
..        ...       ...           ...          ...       ...
496         0        93           675           25        19
497         0        95           210           23        17
498         0        97           398           25        18
499         0        99           678           24        18
500         0       101           201           21        14

[501 rows x 5 columns]

In [30]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y,train_size = 0.8)

In [34]:
Xtrain.shape

(400, 5)

In [35]:
np.savez('./processed_data/crop_data.npz', Xtrain=Xtrain, Ytrain=Ytrain, Xtest=Xtest, Ytest=Ytest)

In [40]:
data = np.load('./processed_data/crop_data.npz', allow_pickle=True)

In [42]:
Xtrain = data['Xtrain']
Ytrain = data['Ytrain']
Xtest = data['Xtest']
Ytest = data['Ytest']
Xtrain.shape

(400, 5)